/*
 * fac_settings.h
 *
 *  Created on: Aug 8, 2025
 *      Author: filippo-castellan
 */

#ifndef INC_FAC_CODE_FAC_SETTINGS_H_
#define INC_FAC_CODE_FAC_SETTINGS_H_

#include "stm32f0xx_hal.h"
#include "FAC_Code/config.h"

enum FAC_SETTINGS_CODE {
	/* MOTORS */
	FAC_SETTINGS_CODE_M1_REVERSED,	// BASIC
	FAC_SETTINGS_CODE_M2_REVERSED,
	FAC_SETTINGS_CODE_M3_REVERSED,
	FAC_SETTINGS_CODE_M1_BRAKE_EN,	// ADVANCED
	FAC_SETTINGS_CODE_M2_BRAKE_EN,
	FAC_SETTINGS_CODE_M3_BRAKE_EN,
	FAC_SETTINGS_CODE_MOTORS_FREQ,
	/* SERVO */
	FAC_SETTINGS_CODE_S1_REVERSED,	// BASIC
	FAC_SETTINGS_CODE_S2_REVERSED,
	FAC_SETTINGS_CODE_S1_MIN_US_VALUE,	// ADVANCED
	FAC_SETTINGS_CODE_S2_MIN_US_VALUE,
	FAC_SETTINGS_CODE_S1_MAX_US_VALUE,
	FAC_SETTINGS_CODE_S2_MAX_US_VALUE,
	FAC_SETTINGS_CODE_SERVOS_FREQ,
	/* BATTERY */
	FAC_SETTINGS_CODE_LOW_BATTERY_VOLTAGE_MV,	// BASIC
	FAC_SETTINGS_CODE_CUTOFF_VOLTAGE_MV,	// ADVANCED
	FAC_SETTINGS_CODE_CUTOFF_DETECTION_TIME,
	/* RECEIVER */
	FAC_SETTINGS_CODE_RECEIVER_TYPE,	// BASIC
	FAC_SETTINGS_CODE_CHANNELS_DEADZONE_PERCENTAGE,
	FAC_SETTINGS_CODE_ARMING_CHANNEL,
	/* MIXES */
	FAC_SETTINGS_CODE_ACTIVE_MIX,	// BASIC
	FAC_SETTINGS_CODE_MIX_INPUT1_CHANNEL,
	FAC_SETTINGS_CODE_MIX_INPUT2_CHANNEL,
	FAC_SETTINGS_CODE_MIX_INPUT3_CHANNEL,
	FAC_SETTINGS_CODE_MIX_INPUT4_CHANNEL,
	FAC_SETTINGS_CODE_MIX_INPUT5_CHANNEL,
	FAC_SETTINGS_CODE_MIX_INPUT6_CHANNEL,
	FAC_SETTINGS_CODE_MIX_INPUT7_CHANNEL,
	FAC_SETTINGS_CODE_MIX_INPUT8_CHANNEL,
	FAC_SETTINGS_CODE_MIX_INPUT1_REVERSED,
	FAC_SETTINGS_CODE_MIX_INPUT2_REVERSED,
	FAC_SETTINGS_CODE_MIX_INPUT3_REVERSED,
	FAC_SETTINGS_CODE_MIX_INPUT4_REVERSED,
	FAC_SETTINGS_CODE_MIX_INPUT5_REVERSED,
	FAC_SETTINGS_CODE_MIX_INPUT6_REVERSED,
	FAC_SETTINGS_CODE_MIX_INPUT7_REVERSED,
	FAC_SETTINGS_CODE_MIX_INPUT8_REVERSED,
	/* SPECIAL FUNCTIONS */
	FAC_SETTINGS_CODE_SPECIAL_FUNCTION1_INPUT_CHANNEL,	// BASIC
	FAC_SETTINGS_CODE_SPECIAL_FUNCTION2_INPUT_CHANNEL,
	FAC_SETTINGS_CODE_SPECIAL_FUNCTION3_INPUT_CHANNEL,
	FAC_SETTINGS_CODE_SPECIAL_FUNCTION4_INPUT_CHANNEL,
	FAC_SETTINGS_CODE_SPECIAL_FUNCTION5_INPUT_CHANNEL,
	FAC_SETTINGS_CODE_SPECIAL_FUNCTION6_INPUT_CHANNEL,
	FAC_SETTINGS_CODE_SPECIAL_FUNCTION7_INPUT_CHANNEL,
	FAC_SETTINGS_CODE_SPECIAL_FUNCTION8_INPUT_CHANNEL,
	FAC_SETTINGS_CODE_SPECIAL_FUNCTION9_INPUT_CHANNEL,
	FAC_SETTINGS_CODE_SPECIAL_FUNCTION10_INPUT_CHANNEL,
	FAC_SETTINGS_CODE_SPECIAL_FUNCTION11_INPUT_CHANNEL,
	FAC_SETTINGS_CODE_SPECIAL_FUNCTION12_INPUT_CHANNEL,
	FAC_SETTINGS_CODE_SPECIAL_FUNCTION13_INPUT_CHANNEL,
	FAC_SETTINGS_CODE_SPECIAL_FUNCTION14_INPUT_CHANNEL,
	FAC_SETTINGS_CODE_SPECIAL_FUNCTION15_INPUT_CHANNEL,
	FAC_SETTINGS_CODE_SPECIAL_FUNCTION16_INPUT_CHANNEL,
	FAC_SETTINGS_CODE_SPECIAL_FUNCTION17_INPUT_CHANNEL,
	FAC_SETTINGS_CODE_SPECIAL_FUNCTION18_INPUT_CHANNEL,
	FAC_SETTINGS_CODE_SPECIAL_FUNCTION19_INPUT_CHANNEL,
	FAC_SETTINGS_CODE_SPECIAL_FUNCTION20_INPUT_CHANNEL,
	/* MAPPER */
	/*
	 * Remember: 100 is mix prefix, 200 is spec. funct. prefix
	 * (ex: FAC_SETTINGS_CODE_MAPPER_M1 = 100+1 means that motor1
	 *  will have the value of the second (100+0 is the first)
	 *  output of the mix active)
	 */
	FAC_SETTINGS_CODE_MAPPER_M1, // BASIC
	FAC_SETTINGS_CODE_MAPPER_M2,
	FAC_SETTINGS_CODE_MAPPER_M3,
	FAC_SETTINGS_CODE_MAPPER_S1,
	FAC_SETTINGS_CODE_MAPPER_S2,

	/* FIRMWARE VERSION */
	FAC_SETTINGS_CODE_FIRMWARE_VERSION,
//.... ecc.
	FAC_SETTINGS_CODE_LAST	// just to have the last code possible, useful for for loop
};

#define USB_SERIAL_TIMEOUT 5	// ms between two different command

enum FAC_USB_COMMAND_CODE {
	FAC_USB_COMMAND_READ_VALUE,
	FAC_USB_COMMAND_READ_RANGE,
	FAC_USB_COMMAND_WRITE,
	FAC_USB_COMMAND_PING,
	FAC_USB_COMMAND_TELEMETRY_REQUEST,
	FAC_USB_COMMAND_TELEMETRY_RESPONSE,
	FAC_USB_COMMAND_SAVE_TO_EEPROM,
	FAC_USB_COMMAND_APPLY_SETTINGS
};

typedef struct Setting {
	uint8_t code;
	uint16_t value;
	uint16_t min_value;
	uint16_t max_value;
} Setting;

void FAC_settings_init(uint8_t bootValue);
uint8_t FAC_settings_command_response();
uint16_t FAC_settings_GET_value(uint8_t code);
void FAC_settings_USB_SEND_setting_ranges(uint8_t code);	// does not need to be globally visible
void FAC_settings_USB_SEND_setting_value(uint8_t code);		// does not need to be globally visible
void FAC_settings_SEND_what_received();						// does not need to be globally visible

#endif /* INC_FAC_CODE_FAC_SETTINGS_H_ */
