/*
 * fac_servo.c
 *
 *  Created on: Aug 4, 2025
 *      Author: filippo-castellan
 */

#include "FAC_Code/fac_servo.h"

#include "main.h"

static Servo servo1;
static Servo servo2;
static Servo *servos[2];	// list of pointer to available servos

/* STATIC FUNCTION PROTORYPES */

/* FUNCTION DEFINITION */
/* ----------------------PRIVATE FUNCTIONS---------------------- */
static void FAC_servo_SET_position(uint16_t position){

}

static void FAC_servo_SET_is_enable(uint8_t isEnable){

}

static void FAC_servo_SET_is_reversed(uint8_t isReversed){

}

/* ----------------------PUBBLIC FUNCTIONS---------------------- */
/**
 * @brief 			Initialize all two servos values, and populate the array of pointers. It also initialize the TIM PWM generator
 * @visibility 		Visible everywhere
 * @note			Servos PWM are generated by TIM3 CH3/4
 */
void FAC_servo_init() {


	servos[0] = &servo1;
	servos[1] = &servo2;

	for (int i = 1; i <= SERVOS_NUMBER; i++) {

	}
}

