/*
 * fac_servo.c
 *
 *  Created on: Aug 4, 2025
 *      Author: filippo-castellan
 */

#include "FAC_Code/fac_servo.h"
#include "tim.h"
#include "main.h"

static Servo servo1;
static Servo servo2;
static Servo *servos[2];	// list of pointer to available servos

/* STATIC FUNCTION PROTORYPES */
static void FAC_servo_SET_position(uint8_t servoNumber, uint16_t position);
static void FAC_servo_SET_is_enable(uint8_t servoNumber, uint8_t isEnable);
static void FAC_servo_SET_is_reversed(uint8_t servoNumber, uint8_t isReversed);

/* FUNCTION DEFINITION */
/* ----------------------PRIVATE FUNCTIONS---------------------- */
static void FAC_servo_SET_position(uint8_t servoNumber, uint16_t position) {
	uint16_t p = position;
	if (p > MAX_SERVO_VALUE)	// (MAX_SERVO_VALUE = 999, 1000-1 because zero is counted)
		p = MAX_SERVO_VALUE;
	if (FAC_servo_GET_is_reversed(servoNumber))
		servos[servoNumber - 1]->position = MAX_SERVO_VALUE - p;
}

static void FAC_servo_SET_is_enable(uint8_t servoNumber, uint8_t isEnable) {
	servos[servoNumber - 1]->is_enable = isEnable;
}

static void FAC_servo_SET_is_reversed(uint8_t servoNumber, uint8_t isReversed) {
	servos[servoNumber - 1]->is_reversed = isReversed;
}

static void FAC_servo_SET_servo_freq(uint16_t servoFreq) {
	servos[0]->servo_freq = servoFreq;
	servos[1]->servo_freq = servoFreq;
}

/* ----------------------PUBBLIC FUNCTIONS---------------------- */
uint16_t FAC_servo_GET_position(uint8_t servoNumber) {
	return servos[servoNumber - 1]->position;
}

uint8_t FAC_servo_GET_is_enable(uint8_t servoNumber) {
	return servos[servoNumber - 1]->is_enable;
}

uint8_t FAC_servo_GET_is_reversed(uint8_t servoNumber) {
	return servos[servoNumber - 1]->is_reversed;
}

uint16_t FAC_servo_GET_servo_freq(uint8_t servoNumber) {
	return servos[servoNumber - 1]->servo_freq;
}


/**
 * @brief	Set the new pwm to the corrisposnding channel
 *
 */


/**
 * @brief 			Initialize all two servos values, and populate the array of pointers. It also initialize the TIM PWM generator
 * @visibility 		Visible everywhere
 * @note			Servos PWM are generated by TIM3 CH3/4
 */
void FAC_servo_init() {
	HAL_TIM_PWM_Init(&htim3);
	HAL_TIM_PWM_Start(&htim3, TIM_CHANNEL_3);
	HAL_TIM_PWM_Start(&htim3, TIM_CHANNEL_4);

	servos[0] = &servo1;
	servos[1] = &servo2;

	for (int i = 1; i <= SERVOS_NUMBER; i++) {
		servos[i]->is_enable = FALSE;
		servos[i]->is_reversed = FALSE;
		servos[i]->position = 0;
		servos[i]->servo_freq = 50;
	}
}

